---
- hosts: jenkins
  roles:
  - role: ypsman.docker
    become: true
  tasks:
  - name: Add Jenkins keyfile
    apt_key:
      url: "https://pkg.jenkins.io/debian/jenkins-ci.org.key"
      state: present
    become: true
  - name: Add Jenkins stable APT repository
    apt_repository:
      repo: "deb http://pkg.jenkins.io/debian-stable binary/"
      state: present
    become: true
  - name: Verify Jenkins installation
    apt:
      name: '{{ item  }}'
      update_cache: yes
    with_items:
    - jenkins
    - python-jenkins
    - python-lxml
    become: true 
  - name: Verify GIT installation
    apt:
      name: git
    become: true
  - name: add Jenkins user to docker group
    user:
      name: jenkins
      groups: docker
    become: true
    notify: Jenkins Restart
  - name: Configure git checkout job
    jenkins_job:
     config: "{{ lookup('file', 'templates/config.xml') }}"
     name: InitialPipelineJob	
     password: gD4nvmDMcJcQ7qL3RfomzXTFV
     url: http://192.168.33.99:8080
     user: dennis
  - name: Verify Python-Py for docker modules
    pip:
      name: docker-py
    become: true
  - name: Start a sonarqube container
    docker_container:
      name: sonarcube
      image: sonarqube:6.3.1-alpine
      state: started
      ports:
      - "9000:9000"
      - "9092:9092"
    become: true
  handlers:
  - name: Jenkins Restart
    service:
      name: jenkins
      status: restarted
    become: true
...
